#!/bin/sh -e

kubectl config delete-context "$HUB_DOMAIN_NAME" > /dev/null 2>&1 || echo ""
gcloud container clusters get-credentials "$CLUSTER_NAME" --zone "$ZONE"
kubectl config rename-context "$(kubectl config current-context)" "$HUB_DOMAIN_NAME"
