#!/bin/bash -e

if test -z "$HUB_KUBECONFIG"; then
  HUB_KUBECONFIG="$(dotenv get "HUB_KUBECONFIG" --default "$KUBECONFIG")"
fi
export KUBECONFIG="$HUB_KUBECONFIG"
CLUSTER="$(terraform output -json | jq -r '.gke_cluster.value')"

set -x
kubectl config delete-context "$HUB_DOMAIN_NAME"
gcloud container clusters get-credentials "$CLUSTER" --region "$GOOGLE_REGION"
kubectl config rename-context "$(kubectl config current-context)" "$HUB_DOMAIN_NAME"
