#!/bin/bash -e

gcloud services enable "composer.googleapis.com"

# shellcheck disable=SC2154
if test ! -f "$REQUIREMENTS_TXT"; then
    color w "Creating empty pypi packages file: $(files abspath "$REQUIREMENTS_TXT")"
    cat << EOF > "$REQUIREMENTS_TXT"
# put your packages here
# More info here: https://pip.pypa.io/en/stable/user_guide/#requirements-files

EOF
fi
