#!/bin/sh -xe

SA_SUFFIX=$(echo "$DOMAIN_NAME" | cut -d "." -f1)
SA_NAME=$(echo "$HUB_COMPONENT"-"$SA_SUFFIX" | cut -c1-20)a

gcloud iam service-accounts delete "$SA_NAME"@"$PROJECT".iam.gserviceaccount.com \
    --project="$PROJECT" --quiet

