#!/bin/sh -xe

SA_SUFFIX=$(echo "$DOMAIN_NAME" | cut -d "." -f1)
SA_NAME=$(echo "$HUB_COMPONENT"-"$SA_SUFFIX" | cut -c1-20)a

gcloud iam service-accounts create "$SA_NAME" \
    --project="$PROJECT"

gcloud projects add-iam-policy-binding "$PROJECT" \
    --member "serviceAccount:$SA_NAME@$PROJECT.iam.gserviceaccount.com" \
    --role roles/dns.admin  

gcloud iam service-accounts add-iam-policy-binding \
  --role roles/iam.workloadIdentityUser \
  --member "serviceAccount:$PROJECT.svc.id.goog[$NAMESPACE/external-dns]" \
  "$SA_NAME"@"$PROJECT".iam.gserviceaccount.com
  
kubectl="kubectl --context=$DOMAIN_NAME"

$kubectl annotate serviceaccount --namespace="$NAMESPACE" --overwrite external-dns \
  "iam.gke.io/gcp-service-account=$SA_NAME@$PROJECT.iam.gserviceaccount.com"

$kubectl --namespace="$NAMESPACE" rollout restart deployment external-dns

