#!/bin/sh -xe

SA_SUFFIX=$(echo "$DOMAIN_NAME" | cut -d "." -f1)
SA_NAME="$HUB_COMPONENT"-"$SA_SUFFIX"

kubectl="kubectl --context=$DOMAIN_NAME"

gcloud iam service-accounts delete "$SA_NAME"@"$PROJECT".iam.gserviceaccount.com \
    --project="$PROJECT" --quiet

if $kubectl get -f "issuer-le-gcp.yaml" -o "name" 2>/dev/null; then
    $kubectl delete -f "issuer-le-gcp.yaml"
fi
